### ISSUE TITLE
Share() doesn't work (builtins.AttributeError: 'NoneType' object has no attribute 'popitem')

### ISSUE THREAD

**Issue by aliberto** [lukaszbanasiak/yahoo-finance#29]
I've just installed yahoo finance to try to parse the key facts of some stock with a program I'm beginning to develop: I just don't manage to make it work and I suspect there has been some changes in Yahoo Finance website since the last package update that has affected the ability of the package to work.
When I try to get stock information with the basic Share class, I get an error:
```
>>> import yahoo_finance
>>> yahoo=yahoo_finance.Share('YHOO')
Traceback (most recent call last):
  Python Shell, prompt 5, line 1
  File "C:\Users\PORTABLE\AppData\Local\Programs\Python\Python35-32\Lib\site-packages\yahoo_finance\__init__.py", line 178, in __init__
    self.refresh()
  File "C:\Users\PORTABLE\AppData\Local\Programs\Python\Python35-32\Lib\site-packages\yahoo_finance\__init__.py", line 142, in refresh
    self.data_set = self._fetch()
  File "C:\Users\PORTABLE\AppData\Local\Programs\Python\Python35-32\Lib\site-packages\yahoo_finance\__init__.py", line 181, in _fetch
    data = super(Share, self)._fetch()
  File "C:\Users\PORTABLE\AppData\Local\Programs\Python\Python35-32\Lib\site-packages\yahoo_finance\__init__.py", line 134, in _fetch
    data = self._request(query)
  File "C:\Users\PORTABLE\AppData\Local\Programs\Python\Python35-32\Lib\site-packages\yahoo_finance\__init__.py", line 125, in _request
    _, results = response['query']['results'].popitem()
builtins.AttributeError: 'NoneType' object has no attribute 'popitem'
```
Before this error the command executes itself during a few seconds, as if it were trying to retrieve a webpage for a long time (but I've checked Yahoo Finance and it's perfectly working on my browser).
Do you know what it is caused by and how to fix it?

**Comment by aliberto** [comment]
The problem was mysteriously solved by a reboot...
So a solution for those who read this issue in the future: try to reboot your computer after installing yahoo_finance package.

**Comment by lukaszbanasiak** [comment]
> So a solution for those who read this issue in the future: try to reboot your computer after installing
srsly? :)

**Comment by michaeldickens** [comment]
I am having this same issue. A reboot did not fix it. The error doesn't usually occur, but it happens on maybe one tenth of requests.
